version: 2
jobs:
  build-nodejs:
    docker:
      - image: circleci/node:10-browsers
    working_directory: ~/repo-nodejs
    steps:
      - checkout
      - restore_cache:
          keys:
            - nodejs-v1-deps-{{ checksum "package-lock.json" }}
            # fallback to using the latest cache if no exact match is found
            - nodejs-v1-deps-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: nodejs-v1-deps-{{ checksum "package-lock.json" }}
      - run: npm run lint
      - run: npm run build
      - run: npm test

  build-kotlin:
    docker:
      - image: circleci/openjdk:11-jdk-stretch
    working_directory: ~/repo-kotlin/src-kotlin
    steps:
      - checkout:
          path: ~/repo-kotlin
      - restore_cache:
          keys:
            - kotlin-v1-deps-{{ checksum "pom.xml" }}
            - kotlin-v1-deps-
      - run: ./mvnw dependency:go-offline
      - save_cache:
          paths:
            - ~/.m2
          key: kotlin-v1-deps-{{ checksum "pom.xml" }}
      - run: ./mvnw package
      - store_test_results:
          path: target/surefire-reports
      - store_artifacts:
          path: target/remote-mob-timer-0.0.1-SNAPSHOT.jar

workflows:
  version: 2
  nodejs:
    jobs:
      - build-nodejs
  kotlin:
    jobs:
      - build-kotlin
